name: Events Demo 1
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
  workflow_dispatch:
env:
  MyPAss: 1234

jobs:
  # test:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout Code
  #       uses: actions/checkout@v4

  #     - name: Install Node.js
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: 18 # or your project's Node version

  #     - name: Install Angular CLI
  #       run: npm install -g @angular/cli

  #     - name: Install Dependencies
  #       run: npm install

  #     - name: Run Tests
  #       run: npm test

  build:
    runs-on: ubuntu-latest
    environment: testing
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: Cache Dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: deps-node-modules-${{ hashFiles('**/package-lock.json')}}
      - name: Install Dependencies
        run: npm install
      - name: Build Code
        run: npm run build
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-files
          path: dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Get Code
        uses: actions/checkout@v4

      - name: Get Build files
        uses: actions/download-artifact@v4
        with:
          name: dist-files
          path: ./dist/biodata-system/browser

      - name: Deploy to Vercel
        run: |
          npm install -g vercel
          vercel --prod --yes --token ${{ secrets.VERCEL_TOKEN }} --name biodata-system --cwd ./dist/biodata-system/browser
